apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: my-notebook
spec:
  template:
    spec:
      containers:
        - name: my-notebook
          image: kubeflownotebookswg/jupyter:master
          args:
            [
                "start.sh",
                "lab",
                "--LabApp.token=''",
                "--LabApp.allow_remote_access='True'",
                "--LabApp.allow_root='True'",
                "--LabApp.ip='*'",
                "--LabApp.base_url=/test/my-notebook/",
                "--port=8888",
                "--no-browser",
            ]